#--------------------------login-------------------------
[[redirects]]
  from = "/api/auth/signin"
  to = "https://bioondatabase.herokuapp.com/api/auth/signin"
  status = 200
  force = true
#----------------------GENERAL DATA-----------------------------------
[[redirects]]
  from = "/api/bio-online-columns"
  to = "https://bioondatabase.herokuapp.com/api/bio-online-columns"
  status = 200
  force = true

[[redirects]]
  from = "/api/bio-online-filter-dict"
  to = "https://bioondatabase.herokuapp.com/api/bio-online-filter-dict"
  status = 200
  force = true

[[redirects]]
  from = "/api/search-animal"
  to = "https://bioondatabase.herokuapp.com/api/search-animal"
  status = 200
  force = true

[[redirects]]
  from = "/api/get-bio-online-localities"
  to = "https://bioondatabase.herokuapp.com/api/get-bio-online-localities"
  status = 200
  force = true

[[redirects]]
  from = "/api/get-genera-species-commonnames"
  to = "https://bioondatabase.herokuapp.com/api/get-genera-species-commonnames"
  status = 200
  force = true

[[redirects]]
  from = "/api/bio-online-search-species-in-localities"
  to = "https://bioondatabase.herokuapp.com/api/bio-online-search-species-in-localities"
  status = 200
  force = true

[[redirects]]
  from = "/api/download-from-localities"
  to = "https://bioondatabase.herokuapp.com/api/download-from-localities"
  status = 200
  force = true




[[redirects]]
  from = "/api/wikiaves-search"
  to = "https://bioondatabase.herokuapp.com/api/wikiaves-search"
  status = 200
  force = true

[[redirects]]
  from = "/api/wikiaves-search-wid"
  to = "https://bioondatabase.herokuapp.com/api/wikiaves-search-wid"
  status = 200
  force = true


[[redirects]]
  from = "/api/ebird-search"
  to = "https://bioondatabase.herokuapp.com/api/ebird-search"
  status = 200
  force = true

[[redirects]]
  from = "/api/inaturalist-search"
  to = "https://bioondatabase.herokuapp.com/api/inaturalist-search"
  status = 200
  force = true

[[redirects]]
  from = "/api/taxonomy-tree"
  to = "https://bioondatabase.herokuapp.com/api/taxonomy-tree"
  status = 200
  force = true



#---------------SPECIES-------------------------------------------------
[[redirects]]
  from = "/api/all-species"
  to = "https://bioondatabase.herokuapp.com/api/all-species"
  status = 200
  force = true
[[redirects]]
  from = "/api/species-by-scientific-name"
  to = "https://bioondatabase.herokuapp.com/api/species-by-scientific-name"
  status = 200
  force = true
[[redirects]]
  from = "/api//api/create-species"
  to = "https://bioondatabase.herokuapp.com/api/create-species"
  status = 200
  force = true
[[redirects]]
  from = "/api/update-species"
  to = "https://bioondatabase.herokuapp.com/api/update-species"
  status = 200
  force = true
[[redirects]]
  from = "/api/delete-species"
  to = "https://bioondatabase.herokuapp.com/api/delete-species"
  status = 200
  force = true


#---------------OBSERVATIONS-------------------------------------------------
[[redirects]]
  from = "/api/observations-by-species-id"
  to = "https://bioondatabase.herokuapp.com/api/observations-by-species-id"
  status = 200
  force = true
[[redirects]]
  from = "/api/create-observation"
  to = "https://bioondatabase.herokuapp.com/api/create-observation"
  status = 200
  force = true
[[redirects]]
  from = "/api/update-observation"
  to = "https://bioondatabase.herokuapp.com/api/update-observation"
  status = 200
  force = true
[[redirects]]
  from = "/api/delete-observation"
  to = "https://bioondatabase.herokuapp.com/api/delete-observation"
  status = 200
  force = true

#------------------------OBSERVERS
[[redirects]]
  from = "/api/find-all-observers"
  to = "https://bioondatabase.herokuapp.com/api/find-all-observers"
  status = 200
  force = true

#---------------LOCALITIES-------------------------------------------------
[[redirects]]
  from = "/api/all-localities"
  to = "https://bioondatabase.herokuapp.com/api/all-localities"
  status = 200
  force = true
[[redirects]]
  from = "/api/species-by-scientific-name"
  to = "https://bioondatabase.herokuapp.com/api/species-by-scientific-name"
  status = 200
  force = true
[[redirects]]
  from = "/api//api/create-locality"
  to = "https://bioondatabase.herokuapp.com/api/create-locality"
  status = 200
  force = true
[[redirects]]
  from = "/api/update-locality"
  to = "https://bioondatabase.herokuapp.com/api/update-locality"
  status = 200
  force = true
[[redirects]]
  from = "/api/delete-locality"
  to = "https://bioondatabase.herokuapp.com/api/delete-locality"
  status = 200
  force = true

  #---------------OBSERVERS-------------------------------------------------
[[redirects]]
  from = "/api/all-observers"
  to = "https://bioondatabase.herokuapp.com/api/all-observers"
  status = 200
  force = true
[[redirects]]
  from = "/api/observers-by-scientific-name"
  to = "https://bioondatabase.herokuapp.com/api/observers-by-scientific-name"
  status = 200
  force = true
[[redirects]]
  from = "/api//api/create-observer"
  to = "https://bioondatabase.herokuapp.com/api/create-observer"
  status = 200
  force = true
[[redirects]]
  from = "/api/update-observer"
  to = "https://bioondatabase.herokuapp.com/api/update-observer"
  status = 200
  force = true
[[redirects]]
  from = "/api/delete-observer"
  to = "https://bioondatabase.herokuapp.com/api/delete-observer"
  status = 200
  force = true

    #---------------DIFFERENCES-------------------------------------------------
